In [22]:
'''
Reference Wafer Marker Pose Accuracy Test 
'''
import cv2
import numpy as np
import matplotlib.pyplot as plt
from cv2 import COLOR_RGB2GRAY
import warnings
warnings.filterwarnings('ignore')

In [60]:
video_low = cv2.VideoCapture('./video/100_1280_960.avi')
video_high = cv2.VideoCapture('./video/100_1600_1200.avi')

w_low  = int(video_low.get(cv2.CAP_PROP_FRAME_WIDTH))
h_low = int(video_low.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps_low = video_low.get(cv2.CAP_PROP_FPS)
frames_low = int(video_low.get(cv2.CAP_PROP_FRAME_COUNT))
print("> low resolution video info : ({},{}@{}), {} frames".format(w_low, h_low, fps_low, frames_low))

w_high  = int(video_low.get(cv2.CAP_PROP_FRAME_WIDTH))
h_high = int(video_low.get(cv2.CAP_PROP_FRAME_HEIGHT))
fps_high = video_low.get(cv2.CAP_PROP_FPS)
frames_high = int(video_high.get(cv2.CAP_PROP_FRAME_COUNT))
print("> high resolution video info : ({},{}@{}), {} frames".format(w_high, h_high, fps_high, frames_high))


mtx = np.matrix([[2517.792, 0., 814.045],[0., 2514.767, 567.330],[0., 0., 1.]])
dist = np.matrix([[-0.361044, 0.154482, 0.000808, 0.000033, 0.]])
newcameramtx_low, roi_low = cv2.getOptimalNewCameraMatrix(mtx, dist, (w_low,h_low), 0, (w_low,h_low))
newcameramtx_high, roi_high = cv2.getOptimalNewCameraMatrix(mtx, dist, (w_low,h_high), 0, (w_low,h_high))

markerdict = cv2.aruco.Dictionary_get(cv2.aruco.DICT_4X4_250)
markerparams = cv2.aruco.DetectorParameters_create()

# for video-1 (1280_960 resolution)
if video_low.isOpened():
    while True:
        ret, frame = video_low.read()
        if ret == True:
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            gray_undist = cv2.undistort(gray, mtx, dist, None, newcameramtx_low)

            corners, ids, rejected = cv2.aruco.detectMarkers(gray, markerdict, parameters=markerparams)
            #print(ids.reshape(1, -1).tolist())
            if 102 in ids:
                rvec, tvec, _ = cv2.aruco.estimatePoseSingleMarkers(corners, 0.04, newcameramtx_low, dist)
                print(tvec)
                print("{}\t{}\t{}".format(tvec.reshape(-1)[0]*100, tvec.reshape(-1)[1]*100, tvec.reshape(-1)[2]*100))
                
            
        else:
            break
    
video_low.release()


[ WARN:0@6108.128] global /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_506zufg7xt/croots/recipe/opencv-suite_1664548331847/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreamer: pipeline have not been created
[ERROR:0@6108.128] global /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_506zufg7xt/croots/recipe/opencv-suite_1664548331847/work/modules/videoio/src/cap.cpp (166) open VIDEOIO(GSTREAMER): raised OpenCV exception:

OpenCV(4.6.0) /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_506zufg7xt/croots/recipe/opencv-suite_1664548331847/work/modules/core/src/utils/filesystem.cpp:580: error: (-213:The function/feature is not implemented)  in function 'exists'


[ WARN:0@6108.132] global /private/var/folders/sy/f16zz6x50xz3113nwtb9bvq00000gp/T/abs_506zufg7xt/croots/recipe/opencv-suite_1664548331847/work/modules/videoio/src/cap_gstreamer.cpp (862) isPipelinePlaying OpenCV | GStreamer warning: GStreame

> low resolution video info : (1280,960@50.0), 149 frames
> high resolution video info : (1280,960@50.0), 148 frames
[[[-0.32489303  0.18773784  1.30250674]]

 [[ 0.13684294  0.18549558  1.31314225]]

 [[-0.2818572  -0.03362381  1.1236631 ]]

 [[-0.08028848 -0.03390233  1.11787586]]

 [[ 0.11995537 -0.03654569  1.14714782]]

 [[-0.28344251 -0.23107502  1.12742902]]

 [[ 0.11489773 -0.23345208  1.13867209]]

 [[-0.08339512 -0.23154939  1.1278138 ]]]
-32.48930319501275	18.773784227491284	130.2506742431525
[[[-0.32323992  0.18672854  1.29755828]]

 [[ 0.11892778  0.16086214  1.14226522]]

 [[-0.28522487 -0.03428898  1.13770556]]

 [[-0.07995483 -0.03386676  1.11181794]]

 [[ 0.11995537 -0.03654569  1.14714782]]

 [[-0.28527398 -0.23228216  1.13313409]]

 [[ 0.11494936 -0.23324939  1.13698272]]

 [[-0.08371904 -0.23274704  1.13368752]]]
-32.32399183947845	18.672854310213825	129.7558284202813
[[[ 0.11892778  0.16086214  1.14226522]]

 [[-0.32061643  0.18537373  1.2880809 ]]

 [[-0.28473182 

In [46]:
# for video-1 (1280_960 resolution)
count = 0
if video_low.isOpened():
    while True:
        ret, frame = video_low.read()
        count += 1
        if ret == True:
            gray = cv2.cvtColor(frame, cv2.COLOR_BGR2GRAY)
            gray = cv2.undistort(gray, mtx, dist, None, newcameramtx_low)

            (corners, ids, rejected) = cv2.aruco.detectMarkers(gray, markerdict, parameters=markerparams)
            
            if 102 in ids:
                print("ok")
                rvec, tvec, _ = cv2.aruco.estimatePoseSingleMarkers(corners, 0.04, newcameramtx_low, dist)
                print(tvec)
                
            
        else:
            break
    
video_low.release()



ok
[[[ 0.13966424  0.18800651  1.3306444 ]]

 [[-0.2725439  -0.0325179   1.11252162]]

 [[-0.07686171 -0.03383814  1.15117771]]

 [[ 0.12172158 -0.03569696  1.16182728]]

 [[-0.27326924 -0.22793266  1.09443042]]

 [[ 0.11720563 -0.23336974  1.14044764]]

 [[-0.07809535 -0.22935774  1.12231911]]]
ok
[[[ 0.13806428  0.18487267  1.31052491]]

 [[-0.27143882 -0.03246941  1.10753402]]

 [[-0.07599331 -0.03326678  1.14093585]]

 [[ 0.12172158 -0.03569696  1.16182728]]

 [[-0.27394857 -0.22842086  1.09741693]]

 [[ 0.11720563 -0.23336974  1.14044764]]

 [[-0.07864628 -0.23041115  1.12668184]]]
ok
[[[ 0.13985314  0.18791057  1.33101576]]

 [[-0.27120927 -0.03261484  1.10772862]]

 [[-0.07616531 -0.03303241  1.14231539]]

 [[ 0.12172158 -0.03569696  1.16182728]]

 [[-0.27420399 -0.22868256  1.09872691]]

 [[ 0.11720563 -0.23336974  1.14044764]]

 [[-0.07864628 -0.23041115  1.12668184]]]
ok
[[[ 0.13955773  0.18763917  1.32853083]]

 [[-0.2725439  -0.0325179   1.11252162]]

 [[-0.07677719 -0.0337

In [ ]:
plt.clf()
    plt.imshow(gray, cmap="gray")
    plt.show()

    if cv2.waitKey(1) & 0xFF == ord('q'):
        break